python prepare_gt_h5.py Bag 1 
python prepare_gt_h5.py Bed 1 
python prepare_gt_h5.py Bed 2 
python prepare_gt_h5.py Bed 3 
python prepare_gt_h5.py Bottle 1 
python prepare_gt_h5.py Bottle 3 
python prepare_gt_h5.py Bowl 1 
python prepare_gt_h5.py Chair 1 
python prepare_gt_h5.py Chair 2 
python prepare_gt_h5.py Chair 3 
python prepare_gt_h5.py Clock 1 
python prepare_gt_h5.py Clock 3 
python prepare_gt_h5.py Dishwasher 1 
python prepare_gt_h5.py Dishwasher 2 
python prepare_gt_h5.py Dishwasher 3 
python prepare_gt_h5.py Display 1 
python prepare_gt_h5.py Display 3 
python prepare_gt_h5.py Door 1 
python prepare_gt_h5.py Door 2 
python prepare_gt_h5.py Door 3 
python prepare_gt_h5.py Earphone 1 
python prepare_gt_h5.py Earphone 3 
python prepare_gt_h5.py Faucet 1 
python prepare_gt_h5.py Faucet 3 
python prepare_gt_h5.py Hat 1 
python prepare_gt_h5.py Keyboard 1 
python prepare_gt_h5.py Knife 1 
python prepare_gt_h5.py Knife 3 
python prepare_gt_h5.py Lamp 1 
python prepare_gt_h5.py Lamp 2 
python prepare_gt_h5.py Lamp 3 
python prepare_gt_h5.py Laptop 1 
python prepare_gt_h5.py Microwave 1 
python prepare_gt_h5.py Microwave 2 
python prepare_gt_h5.py Microwave 3 
python prepare_gt_h5.py Mug 1 
python prepare_gt_h5.py Refrigerator 1 
python prepare_gt_h5.py Refrigerator 2 
python prepare_gt_h5.py Refrigerator 3 
python prepare_gt_h5.py run.sh 
python prepare_gt_h5.py Scissors 1 
python prepare_gt_h5.py StorageFurniture 1 
python prepare_gt_h5.py StorageFurniture 2 
python prepare_gt_h5.py StorageFurniture 3 
python prepare_gt_h5.py Table 1 
python prepare_gt_h5.py Table 2 
python prepare_gt_h5.py Table 3 
python prepare_gt_h5.py TrashCan 1 
python prepare_gt_h5.py TrashCan 3 
python prepare_gt_h5.py Vase 1 
python prepare_gt_h5.py Vase 3 
